---
title: "Kevin's Notes 2024-2025"
output:
  html_document:
    df_print: paged
    toc: yes
    toc_float:
      collapsed: false
    toc_depth: 4
    theme: lumen
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{=html}
<style>
  body .main-container {
    max-width: 1100px;
    font-size: 12pt;
  }
</style>
```

------------------------------------------------------------------------

# Quick Links

+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| -   [LSE Moodle](https://moodle.lse.ac.uk/my/)                                                                                                                                                                         | -   [LSE For You](https://auth.lse.ac.uk/auth/login?service=https%3A%2F%2Flfy.lse.ac.uk%2Fportal%2Fp%2F&renew=true&_gl=1*5ghr49*_gcl_au*MTk0MjQzMTI2MS4xNzEzMzg0NDcy*_ga*OTczMzc3MTk2LjE3MTMzODQ0NzI.*_ga_LWTEVFESYX*MTcyMDU2MDcyMy44Mi4xLjE3MjA1NjA3NjIuMjEuMC4w) |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| -   [LSE Student For You](https://portal.lse.ac.uk/studentservices/s/?_gl=1*1c1xkmp*_gcl_au*MTU2NDcwMzc5MS4xNzIxMjM1NTAz*_ga*OTczMzc3MTk2LjE3MTMzODQ0NzI.*_ga_LWTEVFESYX*MTcyNzM4MTg5Ny4yMDMuMS4xNzI3MzgyNzQyLjguMC4w) | -   [LSE Student Hub](https://studenthub.lse.ac.uk/login)                                                                                                                                                                                                          |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| -   [LSE Outlook Email](https://outlook.office.com/mail/inbox/id/AAQkADU3NWU3M2RlLTk2NmMtNGEyZS1iYTU2LTQ2NTRhZWMzNTMyZQAQAIHp9iDvCC9KkshVxv4XT9U%3D)                                                                   | -   [LSE OneDrive](https://lsecloud-my.sharepoint.com)                                                                                                                                                                                                             |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| -   [Course Regulations](https://www.lse.ac.uk/resources/calendar/programmeRegulations/taughtMasters/2024/MScPoliticalSciencePoliticalScienceAndPoliticalEconomy.htm)                                                  | -   [Course Page](https://www.lse.ac.uk/study-at-lse/Graduate/degree-programmes-2024/MSc-Political-Science-Political-Science-and-Political-Economy)                                                                                                                |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| -   [Stats on LSE](https://info.lse.ac.uk/staff/divisions/academic-registrars-division/systems/what-we-do/statistics-on-lse)                                                                                           | -   [Timetables](https://info.lse.ac.uk/current-students/timetables)                                                                                                                                                                                               |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| -   [Undergrad Modules](https://www.lse.ac.uk/resources/calendar/courseGuides/undergraduate.htm)                                                                                                                       | -   [Postgrad Modules](https://www.lse.ac.uk/resources/calendar/courseGuides/graduate.htm)                                                                                                                                                                         |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

<br />

------------------------------------------------------------------------

# Introductory Courses

### GV4L8 Introductory Maths

**GV4L8 Introductory Maths for Political Science**

Lecturer: Dr. Marta Antonetti

Assessment: None (Pre-Sessional)

+-----------------------------------------------------------------------------------------------+
| 1.  [Sets, Expressions, Functions](https://kevinli03.github.io/notes/GV4L8/1.html)            |
+-----------------------------------------------------------------------------------------------+
| 2.  [Vectors, Matrices, Continuity, Limits](https://kevinli03.github.io/notes/GV4L8/2.html)   |
+-----------------------------------------------------------------------------------------------+
| 3.  [Derivatives, Optimisation, Integrals](https://kevinli03.github.io/notes/GV4L8/3.html)    |
+-----------------------------------------------------------------------------------------------+
| 4.  [Counting, Probability, Random Variables](https://kevinli03.github.io/notes/GV4L8/4.html) |
+-----------------------------------------------------------------------------------------------+

<br />

------------------------------------------------------------------------

### EU409 Basic Economics

**EU409 Basic Economics Concepts for Political Economy**

Lecturer: LSE European Institute

Assessment: N/A (Pre-Sessional)

+--------------------------------------------------------------------------------------------------+
| 1.  [Introduction to Economics, Supply & Demand](https://kevinli03.github.io/notes/EU409/1.html) |
+--------------------------------------------------------------------------------------------------+
| 2.  [Macro I: Supply-Side and Unemployment](https://kevinli03.github.io/notes/EU409/2.html)      |
+--------------------------------------------------------------------------------------------------+
| 3.  Macro II: Aggregate Demand and Macro-Economic Equilibrium                                    |
+--------------------------------------------------------------------------------------------------+
| 4.  Micro I: Household Decisions                                                                 |
+--------------------------------------------------------------------------------------------------+
| 5.  Micro II: Economic Choices of the Firm                                                       |
+--------------------------------------------------------------------------------------------------+
| 6.  Micro III: Market Structure and Imperfections                                                |
+--------------------------------------------------------------------------------------------------+
| 7.  Welfare Economics: Social Welfare and Government                                             |
+--------------------------------------------------------------------------------------------------+
| 8.  Open Economy Macroeconomics                                                                  |
+--------------------------------------------------------------------------------------------------+
| 9.  Unemployment and the Labour Market                                                           |
+--------------------------------------------------------------------------------------------------+

<br />

------------------------------------------------------------------------

# Autumn Term

### GV481 Quantitative Analysis

**GV481 Quantitative Analysis for Political Science**

Lecturer: Dr. Aliz Toth

Formative Assessment: Problem Set 1 (AT W7), Problem Set 2 (AT W9)

Summative Assessment: Coursework (50%, 10 Jan), Exam (50%, Spring)

+---------------------------------------------------------------------------------------------+-------------------------+
| 1.  [Introduction to Quantitative Thinking](https://kevinli03.github.io/notes/GV481/1.html) | 1.  Readings & Problems |
+---------------------------------------------------------------------------------------------+-------------------------+
| 2.  Correlation and OLS                                                                     | 2.  Readings & Problems |
+---------------------------------------------------------------------------------------------+-------------------------+
| 3.  Uncertainty & Hypothesis Testing                                                        | 3.  Readings & Problems |
+---------------------------------------------------------------------------------------------+-------------------------+
| 4.  Causal Inference                                                                        | 4.  Readings & Problems |
+---------------------------------------------------------------------------------------------+-------------------------+
| 5.  Randomised Experiments                                                                  | 5.  Readings & Problems |
+---------------------------------------------------------------------------------------------+-------------------------+
| 6.  READING WEEK                                                                            |                         |
+---------------------------------------------------------------------------------------------+-------------------------+
| 7.  Selection on Observables                                                                | 7.  Readings & Problems |
+---------------------------------------------------------------------------------------------+-------------------------+
| 8.  Instrumental Variables                                                                  | 8.  Readings & Problems |
+---------------------------------------------------------------------------------------------+-------------------------+
| 9.  Regression Discontinuity                                                                | 9.  Readings & Problems |
+---------------------------------------------------------------------------------------------+-------------------------+
| 10. Differences-in-Differences                                                              | 10. Readings & Problems |
+---------------------------------------------------------------------------------------------+-------------------------+
| 11. Survey Experiments                                                                      | 11. Readings & Problems |
+---------------------------------------------------------------------------------------------+-------------------------+

<br />

------------------------------------------------------------------------

### GV4C8 Game Theory

**GV4C8 Game Theory for Political Science**

Lecturer: Prof. Rafael Hortala-Vallve

Assessment: Problem Sets (50%, WT), Exam (50%, January)

+------------------+----------------------------+
| 1.  Session 1    | 1.  Readings               |
+------------------+----------------------------+
| 2.  Session 2    | 2.  Readings & Problem Set |
+------------------+----------------------------+
| 3.  Session 3    | 3.  Readings & Problem Set |
+------------------+----------------------------+
| 4.  Session 4    | 4.  Readings & Problem Set |
+------------------+----------------------------+
| 5.  Session 5    | 5.  Readings & Problem Set |
+------------------+----------------------------+
| 6.  READING WEEK |                            |
+------------------+----------------------------+
| 7.  Session 7    | 7.  Readings & Problem Set |
+------------------+----------------------------+
| 8.  Session 8    | 8.  Readings & Problem Set |
+------------------+----------------------------+
| 9.  Session 9    | 9.  Readings & Problem Set |
+------------------+----------------------------+
| 10. Session 10   | 10. Readings & Problem Set |
+------------------+----------------------------+
| 11. Session 11   | 11. Readings & Problem Set |
+------------------+----------------------------+

<br />

------------------------------------------------------------------------

### MY452A Regression Analysis

**MY452A Applied Regression Analysis**

Lecturer: Prof. Jouni Kuha

Assessment: Exam (100%, Spring)

+-------------------------------------------------------------------------------------+--------------+
| 0.  [Statistical Inference Review](https://kevinli03.github.io/notes/MY452A/0.html) |              |
+-------------------------------------------------------------------------------------+--------------+
| 1.  Introduction to Regression Modelling                                            | 1.  Readings |
+-------------------------------------------------------------------------------------+--------------+
| 2.  Linear Regression I: Basic Elements                                             | 2.  Readings |
+-------------------------------------------------------------------------------------+--------------+
| 3.  Linear Regression II: Types of Explanatory Variables                            | 3.  Readings |
+-------------------------------------------------------------------------------------+--------------+
| 4.  Linear Regression III: Conceptual Questions                                     | 4.  Readings |
+-------------------------------------------------------------------------------------+--------------+
| 5.  Linear Regression IV: Panel & Clustered Data                                    | 5.  Readings |
+-------------------------------------------------------------------------------------+--------------+
| 6.  READING WEEK                                                                    |              |
+-------------------------------------------------------------------------------------+--------------+
| 7.  Binary Logistic Regression I: Definition & Interpretation                       | 7.  Readings |
+-------------------------------------------------------------------------------------+--------------+
| 8.  Binary Logistic Regression II: Inference & Model Selection                      | 8.  Readings |
+-------------------------------------------------------------------------------------+--------------+
| 9.  Multinomial Logistic Regression                                                 | 9.  Readings |
+-------------------------------------------------------------------------------------+--------------+
| 10. Models for Counts                                                               | 10. Readings |
+-------------------------------------------------------------------------------------+--------------+
| 11. Further Topics                                                                  | 11. Readings |
+-------------------------------------------------------------------------------------+--------------+

<br />

------------------------------------------------------------------------

### MY470 Computer Programming

**MY470 Computer Programming (Autumn Term)**

Lecturer: Dr. Milena Tsvetkova

Exam: N/A (Auditing)

+---------------------------------------------------------------------------+-----------------+
| 1.  [What is Computation](https://kevinli03.github.io/notes/MY470/1.html) |                 |
+---------------------------------------------------------------------------+-----------------+
| 2.  Data Types                                                            | 2.  Problem Set |
+---------------------------------------------------------------------------+-----------------+
| 3.  Control Flow                                                          | 3.  Problem Set |
+---------------------------------------------------------------------------+-----------------+
| 4.  Functions                                                             | 4.  Problem Set |
+---------------------------------------------------------------------------+-----------------+
| 5.  Classes                                                               | 5.  Problem Set |
+---------------------------------------------------------------------------+-----------------+
| 6.  READING WEEK                                                          |                 |
+---------------------------------------------------------------------------+-----------------+
| 7.  Testing and Debugging                                                 | 7.  Problem Set |
+---------------------------------------------------------------------------+-----------------+
| 8.  R Programming Language                                                | 8.  Problem Set |
+---------------------------------------------------------------------------+-----------------+
| 9.  Algorithms and Order of Growth                                        | 9.  Problem Set |
+---------------------------------------------------------------------------+-----------------+
| 10. Searching and Sorting Algorithms                                      | 10. Problem Set |
+---------------------------------------------------------------------------+-----------------+
| 11. Tree and Graph Algorithms                                             | 11. Problem Set |
+---------------------------------------------------------------------------+-----------------+

<br />

------------------------------------------------------------------------

# Winter Term

### GV482 Current Issues

**GV482 Political Science and Political Economy: Current Issues**

Lecturer: Prof. Stephane Wolton

Assessment: Coursework (50%, WT), Online Assessment (50%, Spring)

<br />

------------------------------------------------------------------------

### MY457 Causal Inference

**MY457 Causal Inference for Observational and Experimental Studies**

Lecturer: Dr. Daniel De Kadt

Assessment: Take-Home Assessment (100%, Spring)

<br />

------------------------------------------------------------------------

### MY455 Multivariate Analysis

**MY455 Multivariate Analysis and Measurement**

Lecturer: Prof. Jouni Kuha

Assessment: Exam (100%, Spring)

<br />\

------------------------------------------------------------------------

### ST304 Time Series

**ST304 Time Series and Forecasting (Winter Term)**

Lecturer

<br />

------------------------------------------------------------------------

# Other LSE Notes

### EC453 Political Economy

**EC453 Political Economy (Full Year)**

Lecturer: Professor Stephane Wolton

+----------------------------------------------------------+
| 3.  Information Aggregation in Elections                 |
+----------------------------------------------------------+
| 4.  Electoral Competition I                              |
+----------------------------------------------------------+
| 5.  Electoral Competition II                             |
+----------------------------------------------------------+
| 6.  READING WEEK                                         |
+----------------------------------------------------------+
| 7.  Political Agency I                                   |
+----------------------------------------------------------+
| 8.  Political Agency II                                  |
+----------------------------------------------------------+
| 9.  Institutions and Policy Outcomes                     |
+----------------------------------------------------------+
| 10. Politics in Developing Democracies - Corruption      |
+----------------------------------------------------------+
| 11. Politics in Developing Democracies - State Capacity  |
+----------------------------------------------------------+
| 12. Media                                                |
+----------------------------------------------------------+
| 13. Social Media                                         |
+----------------------------------------------------------+
| 14. Interest Groups                                      |
+----------------------------------------------------------+
| 15. Populism                                             |
+----------------------------------------------------------+
| 16. Discrimination I                                     |
+----------------------------------------------------------+
| 17. READING WEEK                                         |
+----------------------------------------------------------+
| 18. Discrimination II: Women in Politics                 |
+----------------------------------------------------------+
| 19. Autocratic Politics I: Elite Behaviour               |
+----------------------------------------------------------+
| 20. Autocratic Politics II: Role of Parliament           |
+----------------------------------------------------------+
| 21. Autocratic Politics III: Role of Media and Elections |
+----------------------------------------------------------+
| 22. Democratisation                                      |
+----------------------------------------------------------+

<br />

------------------------------------------------------------------------

### Topics in Political Economy

**From a Combination of Courses I Find Interesting**

-   IR470 International Political Economy

-   DV464 Democracy and Development

-   EU443 European Models of Capitalism

+-----------------------------------------+-----------+
| 1.  IPE 1st Lecture                     | -   IR470 |
+-----------------------------------------+-----------+
| 2.  IPE Second Lecture                  | -   IR470 |
+-----------------------------------------+-----------+
| 3.  Democracy & Development 3rd Lecture | -   DV464 |
+-----------------------------------------+-----------+
| 4.  European Models of Capitalism       | -   EU443 |
+-----------------------------------------+-----------+

<br />

------------------------------------------------------------------------

<br />

### Topics in Methodology

<br />

------------------------------------------------------------------------

### PSPE Research Seminars

Seminar Conveners: Dr. Aliz Toth, Dr. Carl Muller Crepon, Dr. Nirvikar Jassal

Location: SAL.3.05 Tuesday 14:00 - 15:30

+-------------------------------------------------+-------------------------------------+
| 1.  Are US Tax Policies Increasingly Polarised? | -   Alisa Tazhitdinova (UCSB)       |
+-------------------------------------------------+-------------------------------------+
|                                                 | -   Federica Braccioli (Vienna)     |
+-------------------------------------------------+-------------------------------------+
|                                                 | -   Volha Charnysh (MIT)            |
+-------------------------------------------------+-------------------------------------+
|                                                 | -   Maggie Penn (Emory)             |
+-------------------------------------------------+-------------------------------------+
|                                                 | -   Nina McMurray (Vanderbilt)      |
+-------------------------------------------------+-------------------------------------+
|                                                 | -   Austin Wright (Chicago)         |
+-------------------------------------------------+-------------------------------------+
|                                                 | -   Hunter Rendleman (UC)           |
+-------------------------------------------------+-------------------------------------+
|                                                 | -   Luca Braghieri (Bocconi)        |
+-------------------------------------------------+-------------------------------------+
|                                                 | -   Dominik Hangartner (ETH Zurich) |
+-------------------------------------------------+-------------------------------------+
|                                                 | -   Judith Spirig (UCL)             |
+-------------------------------------------------+-------------------------------------+

<br />

------------------------------------------------------------------------

# Short Guides

### 
