---
title: "Introduction to Proofs and Logic"
subtitle: "Kevin's PSPE Notes: Proof and Analysis"
format:
    html:
        page-layout: article
        grid:
          sidebar-width: 350px
          body-width: 700px
          margin-width: 250px
          gutter-width: 2em
        fontsize: 12pt
        theme: default
        toc: TRUE
        toc-depth: 3
        toc-location: left
        toc-expand: true
        toc-title: "Table of Contents"
        mainfont: "Computer Modern"
        title-block-banner: true
        classoption: fleqn
        html-math-method: katex
editor: visual
---

Use the sidebar for navigation.

------------------------------------------------------------------------

# **Logic Operands**

### Negation

The negation of a statement $P$, is $\neg P$.

-   So if $P$ is true, $\neg P$ is false.
-   If $P$ is false, $\neg P$ is true.

<br />

### Conjunction (And)

Suppose $P$ and $Q$ are two statements.

$P$ **and** $Q$ are denoted $P \wedge Q$.

The **and** operator means both statements must be true, if $P \wedge Q$ is true.

-   If $P$ is true and $Q$ is true, then $P \wedge Q$ is true.
-   If $P$ is true and $Q$ is false, then $P \wedge Q$ is false.
-   If $P$ is false and $Q$ is true, then $P \wedge Q$ is false.
-   If $P$ is false and $Q$ is false, then $P \wedge Q$ is false.

<br />

### Disjunction (Or)

Suppose $P$ and $Q$ are two statements.

$P$ **or** $Q$ is denoted $P \vee Q$.

The **or** operator means that at least one is true, if $P \vee Q$ is true.

-   If $P$ is true and $Q$ is true, $P \vee Q$ is true.
-   If $P$ is true and $Q$ is false, $P \vee Q$ is true.
-   If $P$ is false and $Q$ is true, $P \vee Q$ is true.
-   If $P$ is false and $Q$ is false, $P \vee Q$ is false.

<br />

### Implication

Suppose $P$ and $Q$ are two statements.

$P$ **implies** $Q$ is denoted as $P \Rightarrow Q$. $P$ is the premise, and $Q$ is the conclusion.

-   If $P$ is true, and $Q$ is true, $P \Rightarrow Q$ is true.
-   If $P$ is true, and $Q$ is false, $P \Rightarrow Q$ is false (since P is not implying Q if P occurs but Q does not).
-   If $P$ is false, and $Q$ is true, $P \Rightarrow Q$ is true (This might be confusing - but think about this. If $P$ is wearing sunscreen, and that is false, that does not necessarily mean that wearing sunscreen does not prevent sunburn $Q$).
-   If $P$ is false and $Q$ is false, $P \Rightarrow Q$ is true.

Imagine $Q$ is something you care about happening, $P$ is the reason it might happen.

-   Maybe $Q$ is I do not get sunburned. $P$ is the reason - you are wearing sunscreen.

<br />

### Equivalence (If and only If)

If $P \Rightarrow Q$, **and** $Q \Rightarrow P$, this means $Q$ is true precisely when $P$ is. $Q$ is true **if and only if** $P$ is true.

Then $P$ and $Q$ are called **equivalent** statements, notated $P \Leftrightarrow Q$.

-   If $P$ is true and $Q$ is true, then $P \Leftrightarrow Q$ is true.
-   If $P$ is true and $Q$ is false, then $P \Leftrightarrow Q$ is false.
-   If $P$ is false and $Q$ is true, then $P \Leftrightarrow Q$ is false.
-   If $P$ is false and $Q$ is false, then $P \Leftrightarrow Q$ is true.

<br />

<br />

------------------------------------------------------------------------

# **Mathematical Statements**

### Universal Statement

A universal statement is one that makes an assertion about **all** natural numbers, or **all** of something.

For example, the below is a universal statement/proposition.

> For every natural number $n$, the number $n^2+3n$ is even.

This statement is either true or false, and this is not dependent on $n$.

<br />

### Existential Statements

An existential statement asserts the existence of a particular number.

For example, the below is an existential statement:

> There is a natural number $n$, such that $2n = 2^n$

This statement is either true or false, and this does not depend on $n$.

<br />

### Implication

An implication is a statement with a **predicate** (condition).

For example, take the following implication:

> If $n$ is even, then $n^2$ is even.

[Proof]{.underline}:

> Given $n \in \mathbb N$, suppose $2 | n$ ($n$ is divisible by 2)
>
> So let $k \in \mathbb Z$ s.t. $n = 2k$.
>
> $n^2 = (2k)^2 = 2(2k^2)$, so let $l = 2k^2$.
>
> So, $n^2 = 2(l)$, so $n^2$ is even.
