---
title: "Welcome to Computer Programming"
subtitle: "Session 1, MY470"
output:
  html_document:
    df_print: paged
    toc: yes
    toc_float:
      collapsed: false
    toc_depth: 4
    theme: lumen
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{=html}
<style>
  body .main-container {
    max-width: 1100px;
    font-size: 12pt;
  }
</style>
```
[MY470 Homepage](https://kevinli03.github.io/notes/#MY470_Computer_Programming)

------------------------------------------------------------------------

# Introduction

### Use of Computer Programming

Why do social scientists need computer programming?

-   Collect data:

    -   Such as crawling websites, using APIs

    -   Online surveys and experiments

    -   Computational models and simulations

-   Manage, analyse, and visualise data

    -   Large data (often too large for Excel and other common programmes)

    -   Non-rectangular data, like text and networks

-   Independence: don't need others to make software for some analysis - we can programme them ourselves

-   Collaborate, as programming allows us to generate and share reproducible workflows

<br />

### Coding vs. Programming

Coding is only one aspect of programming

-   Translating our intentions/problem solving strategies into code that machines can understand

Programming is more than coding:

-   Problem analysis: if you have a certain problem, how do we solve this problem in a way that the computer can understand

-   Algorithm design: we often have resource constraints (storage, computing power, etc.), and we have to design our solution in a way that meets these constraints, and is efficient

-   Coding: encode the design you have created into syntax the machine can understand

-   Testing: make sure that our code is working properly, finding the correct results we are interested in. Make sure our solution is robust

-   Debugging: find and address bugs and mistakes

<br />

### Computational Thinking

Computational thinking is a thought process:

-   Formulating a problem

-   Expressing its solution in a way that computer or human can carry it out.

The characteristics of computational thinking are:

-   Conceptualising: thinking at multiple levels of abstraction - subdividing the problem into small parts, and link it to thinks we know how to approach

-   Human thinking: requires cleverness and imagination

-   Combines mathematical and engineering thinking: have to consider the constraints of our computers

-   For everyone: just like reading, writing, arithmetic

<br />

------------------------------------------------------------------------

[MY470 Homepage](https://kevinli03.github.io/notes/#MY470_Computer_Programming)

# Programming Languages

### Algorithms

An algorithm is a procedure - that takes inputs, and produces an output

-   Ex. a Recipe - how to combine ingredients (inputs) into a food (output)

Algorithms can be specified in human language and programming language

-   We often first write "psuedo-code" - writing the steps in english to help view the steps of the algorithm

<br />

### Computers & Languages

Computers are machines that perform calculations, either built-in or user defined. They store the result of the calculations

Markup languages, also called scripting, are used to structure and present data

-   Like HTML, Latex, Markdown

-   They have tags to instruct how to render certain elements in order to present it - rendering done through a program (like a browser)

Programming languages transform and generate data

-   Like Python, R, C++, Java

-   Usually speaks to the hardware - not through a programme

<br />

### Properties of Languages

Programming Languages is a language used to specify a set of instructions for a computer to execute. The properties of programming languages include:

1.  Primitive constructs: basic units in which we store/assign data, and basic operations to manipulate it
    -   Literals: anything that you can input in the program that will be evaluated correctly/understood (ex. a number, a string, a boolean, etc.)
    -   Infix Operators: operations on the literals (ex. add, subtract, multiply, powers, concatenating strings, etc.)
2.  Syntax: rules of how these elements come together
    -   What symbols to use, what functions to use, etc.
    -   The "grammar" of a programming language
    -   Ex. to add, we use "+", not any other symbol
3.  Static Semantics: whether the strings of different elements are meaningful for a computer
    -   Rules for forming syntax, that actually makes sense
    -   Ex, while *"kevin" + 1* is syntactically correct, that makes no sense to the computer - how do you add a string "kevin" with the number "1"?
4.  Semantics: the meaning associated with a expression
    -   What does the operation I just did mean? Is it what I want it to mean?
    -   Difficult to diagnose when it goes wrong - there's no error appearing like the others, it is about interpretation of the result

<br />

### Types of Languages

Low-Level vs. High-Level Languages:

-   Low-level languages speak directly to the hardware

-   High-level languages speak to lower level languages, who then speak to the hardware (more layers)

-   Lower level languages are more efficient, and require less memory - however, can be harder to learn and interpret, and are less intuitive

<br />

General vs. Application Targeted Languages

-   Some programming languages are meant for specific tasks, while others can do a variety of tasks

-   Python is a general language - you can do almost everything with it

-   Some languages are designed for specific tasks - maybe like networks, etc.

<br />

Interpreted vs. Compiled Languages

-   For some languages, you don't just type the code, and run it right away. You need to compile your code into a form that the machine can understand before it runs.

-   Python and R do not need to be compiled before running

<br />

### Computer Programs

Computer Programs are a sequence of definitions and commands, that instruct the computer to do something

-   Programs are executed by the language interpreter (called the "shell")

-   They can be typed directly in the shell, or we can store it in the file, and run the file itself

<br />

------------------------------------------------------------------------

[MY470 Homepage](https://kevinli03.github.io/notes/#MY470_Computer_Programming)

# Objects

### Data Types

Programs manipulate objects. Objects have two types:

-   Scalar: indivisible data (can't really find structure within it)

    -   Integers (a positive or negative whole number)

    -   Floating point (decimals)

    -   These are just one object - they can't be further subdivided

-   Non-scalar: with internal structure (multiple elements within)

    -   Lists - an object with multiple elements (ex. [3, 7, "j"] )

    -   Strings (in python) - where each letter/character is an element

Expressions combine objects and operators

<br />

### Variables

Often, we want to store our objects, so we can use them later

-   Variables associate objects with a name

-   In python, you use the equal sign

For example, $a,b,c$ are variables (in python, we use $=$ to assign variables).

```{python}
a = 3.14
b = 11.2
c = a*(b**2) #** means power
```

<br />

To call a variable, simply type that variable and run. Alternatively, you can use the print function:

```{python}

# print variable a
a

# another way
print(a)
```

<br />

Generally, we want to name variables based on what they contain

-   This makes it legible to humans who are reading the code

-   Helps with debugging and finding issues

-   Also, include comments (with "\#")

<br />

------------------------------------------------------------------------

[MY470 Homepage](https://kevinli03.github.io/notes/#MY470_Computer_Programming)
